# Temporary workflow on master to trigger actions tab
name: run-typhoon-model
on:
  workflow_dispatch:

jobs:
  run-typhoon-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
